### ISSUE TITLE
关于check_sum和sum的问题

### ISSUE THREAD

**Issue by Fww66** [MagicPrince666/atk_imu901_ros2#1]
**一开始可以正常运行，之后就一直报错**
![Image_20240822104638](https://github.com/user-attachments/assets/fd47fcb8-8bf0-4116-a9dc-07f91c0d3eec)
![Image_20240822105031](https://github.com/user-attachments/assets/24003e8b-0f7a-4f3a-b851-955131bb9f43)
![Image_20240822104823](https://github.com/user-attachments/assets/73d8def0-3c7c-4a40-bbd0-84b3a51bc69a)

**Comment by MagicPrince666** [comment]
已合并补丁
